spring.application.name=plural

spring.datasource.url=jdbc:postgresql://localhost:5432/colegio_plural
spring.datasource.username=postgres
spring.datasource.password=aluno

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080